M48
; DRILL file {KiCad 8.99.0-3334-g98ae574c78} date 2024-12-15T17:17:29-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-15T17:17:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.99.0-3334-g98ae574c78
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X186.949Y-73.282
X186.949Y-79.062
T2
X137.11Y-75.98
T3
X138.055Y-102.675
M30
