M48
; DRILL file {KiCad 7.99.0-957-g18dd623122} date 2023 July 20, Thursday 21:46:05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-20T21:46:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-957-g18dd623122
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.2341Y-3.389
T2
X5.232Y-4.563
T0
M30
