M48
; DRILL file {KiCad 7.99.0-957-g18dd623122} date 2023 July 11, Tuesday 11:10:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-11T11:10:07+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-957-g18dd623122
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.0292Y-3.5536
X5.702Y-3.5536
T2
X4.95Y-4.749
X6.863Y-3.303
T0
M30
