M48
; DRILL file {KiCad 7.99.0-3012-g423a5b9961} date 2023-12-08T20:57:24-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-08T20:57:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-3012-g423a5b9961
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.766Y-3.409
T2
X4.811Y-4.817
X6.372Y-3.34
T0
M30
